package cn.xvkang.entity;

import java.io.Serializable;

public class Kemuzuhe implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kemuzuhe.id
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kemuzuhe.name
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kemuzuhe.pid
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kemuzuhe.canselect
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    private Integer canselect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kemuzuhe.fullname
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    private String fullname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kemuzuhe.sort
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kemuzuhe.code
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kemuzuhe
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kemuzuhe.id
     *
     * @return the value of kemuzuhe.id
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kemuzuhe.id
     *
     * @param id the value for kemuzuhe.id
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kemuzuhe.name
     *
     * @return the value of kemuzuhe.name
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kemuzuhe.name
     *
     * @param name the value for kemuzuhe.name
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kemuzuhe.pid
     *
     * @return the value of kemuzuhe.pid
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kemuzuhe.pid
     *
     * @param pid the value for kemuzuhe.pid
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kemuzuhe.canselect
     *
     * @return the value of kemuzuhe.canselect
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public Integer getCanselect() {
        return canselect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kemuzuhe.canselect
     *
     * @param canselect the value for kemuzuhe.canselect
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public void setCanselect(Integer canselect) {
        this.canselect = canselect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kemuzuhe.fullname
     *
     * @return the value of kemuzuhe.fullname
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kemuzuhe.fullname
     *
     * @param fullname the value for kemuzuhe.fullname
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public void setFullname(String fullname) {
        this.fullname = fullname == null ? null : fullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kemuzuhe.sort
     *
     * @return the value of kemuzuhe.sort
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kemuzuhe.sort
     *
     * @param sort the value for kemuzuhe.sort
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kemuzuhe.code
     *
     * @return the value of kemuzuhe.code
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kemuzuhe.code
     *
     * @param code the value for kemuzuhe.code
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }
}