package cn.xvkang.entity;

public class Permission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.id
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.parent_id
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.name
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.describe
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    private String describe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.url
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.icon
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.num
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.code
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.spread
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    private String spread;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.attribute
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    private Integer attribute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.type
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.level
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.time
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.checked
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    private Integer checked;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.id
     *
     * @return the value of permission.id
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.id
     *
     * @param id the value for permission.id
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.parent_id
     *
     * @return the value of permission.parent_id
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.parent_id
     *
     * @param parentId the value for permission.parent_id
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.name
     *
     * @return the value of permission.name
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.name
     *
     * @param name the value for permission.name
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.describe
     *
     * @return the value of permission.describe
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.describe
     *
     * @param describe the value for permission.describe
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.url
     *
     * @return the value of permission.url
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.url
     *
     * @param url the value for permission.url
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.icon
     *
     * @return the value of permission.icon
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.icon
     *
     * @param icon the value for permission.icon
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.num
     *
     * @return the value of permission.num
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.num
     *
     * @param num the value for permission.num
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.code
     *
     * @return the value of permission.code
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.code
     *
     * @param code the value for permission.code
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.spread
     *
     * @return the value of permission.spread
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public String getSpread() {
        return spread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.spread
     *
     * @param spread the value for permission.spread
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public void setSpread(String spread) {
        this.spread = spread == null ? null : spread.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.attribute
     *
     * @return the value of permission.attribute
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public Integer getAttribute() {
        return attribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.attribute
     *
     * @param attribute the value for permission.attribute
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public void setAttribute(Integer attribute) {
        this.attribute = attribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.type
     *
     * @return the value of permission.type
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.type
     *
     * @param type the value for permission.type
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.level
     *
     * @return the value of permission.level
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.level
     *
     * @param level the value for permission.level
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.time
     *
     * @return the value of permission.time
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.time
     *
     * @param time the value for permission.time
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.checked
     *
     * @return the value of permission.checked
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public Integer getChecked() {
        return checked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.checked
     *
     * @param checked the value for permission.checked
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public void setChecked(Integer checked) {
        this.checked = checked;
    }
}