package cn.xvkang.entity;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.id
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.name
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.value
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.describe
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    private String describe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.time
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.state
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.id
     *
     * @return the value of role.id
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.id
     *
     * @param id the value for role.id
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.name
     *
     * @return the value of role.name
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.name
     *
     * @param name the value for role.name
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.value
     *
     * @return the value of role.value
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.value
     *
     * @param value the value for role.value
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.describe
     *
     * @return the value of role.describe
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.describe
     *
     * @param describe the value for role.describe
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.time
     *
     * @return the value of role.time
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.time
     *
     * @param time the value for role.time
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.state
     *
     * @return the value of role.state
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.state
     *
     * @param state the value for role.state
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }
}