package cn.xvkang.entity;

public class RolePermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.id
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.permission_id
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    private String permissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.role_id
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.menu_attribute
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    private Integer menuAttribute;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.id
     *
     * @return the value of role_permission.id
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.id
     *
     * @param id the value for role_permission.id
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.permission_id
     *
     * @return the value of role_permission.permission_id
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public String getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.permission_id
     *
     * @param permissionId the value for role_permission.permission_id
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public void setPermissionId(String permissionId) {
        this.permissionId = permissionId == null ? null : permissionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.role_id
     *
     * @return the value of role_permission.role_id
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.role_id
     *
     * @param roleId the value for role_permission.role_id
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.menu_attribute
     *
     * @return the value of role_permission.menu_attribute
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public Integer getMenuAttribute() {
        return menuAttribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.menu_attribute
     *
     * @param menuAttribute the value for role_permission.menu_attribute
     *
     * @mbg.generated Sun Apr 21 15:59:23 CST 2019
     */
    public void setMenuAttribute(Integer menuAttribute) {
        this.menuAttribute = menuAttribute;
    }
}