package cn.xvkang.entity;

import java.io.Serializable;

public class Student implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.phone
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.idcard
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    private String idcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.select_kemuzuheid
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    private Integer selectKemuzuheid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.gender
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    private Integer gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.select_kemuzuhe_again
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    private Integer selectKemuzuheAgain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.xuejihao
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    private String xuejihao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.niji_name
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    private String nijiName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.banji_name
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    private String banjiName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.jibu_name
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    private String jibuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.banji_code
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    private String banjiCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.current_address
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    private String currentAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.contact_address
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    private String contactAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.contact_telphone
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    private String contactTelphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.home_address
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    private String homeAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.father_phone
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    private String fatherPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.mother_phone
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    private String motherPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.yunxiaoyuan_name
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    private String yunxiaoyuanName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.yunxiaoyuan_banjicode
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    private String yunxiaoyuanBanjicode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.unique_code
     *
     * @mbg.generated Wed Apr 24 10:17:13 CST 2019
     */
    private String uniqueCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.gongfei_zifei
     *
     * @mbg.generated Wed Apr 24 10:17:13 CST 2019
     */
    private String gongfeiZifei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.zizhusheng
     *
     * @mbg.generated Wed Apr 24 10:17:13 CST 2019
     */
    private String zizhusheng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.jiandanglikahu
     *
     * @mbg.generated Wed Apr 24 10:17:13 CST 2019
     */
    private String jiandanglikahu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.yunxiaoyuan_phone
     *
     * @mbg.generated Wed Apr 24 10:17:13 CST 2019
     */
    private String yunxiaoyuanPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student
     *
     * @mbg.generated Wed Apr 24 10:17:13 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.phone
     *
     * @return the value of student.phone
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.phone
     *
     * @param phone the value for student.phone
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.idcard
     *
     * @return the value of student.idcard
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.idcard
     *
     * @param idcard the value for student.idcard
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.select_kemuzuheid
     *
     * @return the value of student.select_kemuzuheid
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public Integer getSelectKemuzuheid() {
        return selectKemuzuheid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.select_kemuzuheid
     *
     * @param selectKemuzuheid the value for student.select_kemuzuheid
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public void setSelectKemuzuheid(Integer selectKemuzuheid) {
        this.selectKemuzuheid = selectKemuzuheid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.gender
     *
     * @return the value of student.gender
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.gender
     *
     * @param gender the value for student.gender
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.select_kemuzuhe_again
     *
     * @return the value of student.select_kemuzuhe_again
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public Integer getSelectKemuzuheAgain() {
        return selectKemuzuheAgain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.select_kemuzuhe_again
     *
     * @param selectKemuzuheAgain the value for student.select_kemuzuhe_again
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public void setSelectKemuzuheAgain(Integer selectKemuzuheAgain) {
        this.selectKemuzuheAgain = selectKemuzuheAgain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.xuejihao
     *
     * @return the value of student.xuejihao
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public String getXuejihao() {
        return xuejihao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.xuejihao
     *
     * @param xuejihao the value for student.xuejihao
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public void setXuejihao(String xuejihao) {
        this.xuejihao = xuejihao == null ? null : xuejihao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.niji_name
     *
     * @return the value of student.niji_name
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public String getNijiName() {
        return nijiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.niji_name
     *
     * @param nijiName the value for student.niji_name
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public void setNijiName(String nijiName) {
        this.nijiName = nijiName == null ? null : nijiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.banji_name
     *
     * @return the value of student.banji_name
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public String getBanjiName() {
        return banjiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.banji_name
     *
     * @param banjiName the value for student.banji_name
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public void setBanjiName(String banjiName) {
        this.banjiName = banjiName == null ? null : banjiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.jibu_name
     *
     * @return the value of student.jibu_name
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public String getJibuName() {
        return jibuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.jibu_name
     *
     * @param jibuName the value for student.jibu_name
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public void setJibuName(String jibuName) {
        this.jibuName = jibuName == null ? null : jibuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.banji_code
     *
     * @return the value of student.banji_code
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public String getBanjiCode() {
        return banjiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.banji_code
     *
     * @param banjiCode the value for student.banji_code
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public void setBanjiCode(String banjiCode) {
        this.banjiCode = banjiCode == null ? null : banjiCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.current_address
     *
     * @return the value of student.current_address
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public String getCurrentAddress() {
        return currentAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.current_address
     *
     * @param currentAddress the value for student.current_address
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public void setCurrentAddress(String currentAddress) {
        this.currentAddress = currentAddress == null ? null : currentAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.contact_address
     *
     * @return the value of student.contact_address
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public String getContactAddress() {
        return contactAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.contact_address
     *
     * @param contactAddress the value for student.contact_address
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public void setContactAddress(String contactAddress) {
        this.contactAddress = contactAddress == null ? null : contactAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.contact_telphone
     *
     * @return the value of student.contact_telphone
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public String getContactTelphone() {
        return contactTelphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.contact_telphone
     *
     * @param contactTelphone the value for student.contact_telphone
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public void setContactTelphone(String contactTelphone) {
        this.contactTelphone = contactTelphone == null ? null : contactTelphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.home_address
     *
     * @return the value of student.home_address
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public String getHomeAddress() {
        return homeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.home_address
     *
     * @param homeAddress the value for student.home_address
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public void setHomeAddress(String homeAddress) {
        this.homeAddress = homeAddress == null ? null : homeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.father_phone
     *
     * @return the value of student.father_phone
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public String getFatherPhone() {
        return fatherPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.father_phone
     *
     * @param fatherPhone the value for student.father_phone
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public void setFatherPhone(String fatherPhone) {
        this.fatherPhone = fatherPhone == null ? null : fatherPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.mother_phone
     *
     * @return the value of student.mother_phone
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public String getMotherPhone() {
        return motherPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.mother_phone
     *
     * @param motherPhone the value for student.mother_phone
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public void setMotherPhone(String motherPhone) {
        this.motherPhone = motherPhone == null ? null : motherPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.yunxiaoyuan_name
     *
     * @return the value of student.yunxiaoyuan_name
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public String getYunxiaoyuanName() {
        return yunxiaoyuanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.yunxiaoyuan_name
     *
     * @param yunxiaoyuanName the value for student.yunxiaoyuan_name
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public void setYunxiaoyuanName(String yunxiaoyuanName) {
        this.yunxiaoyuanName = yunxiaoyuanName == null ? null : yunxiaoyuanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.yunxiaoyuan_banjicode
     *
     * @return the value of student.yunxiaoyuan_banjicode
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public String getYunxiaoyuanBanjicode() {
        return yunxiaoyuanBanjicode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.yunxiaoyuan_banjicode
     *
     * @param yunxiaoyuanBanjicode the value for student.yunxiaoyuan_banjicode
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public void setYunxiaoyuanBanjicode(String yunxiaoyuanBanjicode) {
        this.yunxiaoyuanBanjicode = yunxiaoyuanBanjicode == null ? null : yunxiaoyuanBanjicode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.unique_code
     *
     * @return the value of student.unique_code
     *
     * @mbg.generated Wed Apr 24 10:17:13 CST 2019
     */
    public String getUniqueCode() {
        return uniqueCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.unique_code
     *
     * @param uniqueCode the value for student.unique_code
     *
     * @mbg.generated Wed Apr 24 10:17:13 CST 2019
     */
    public void setUniqueCode(String uniqueCode) {
        this.uniqueCode = uniqueCode == null ? null : uniqueCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.gongfei_zifei
     *
     * @return the value of student.gongfei_zifei
     *
     * @mbg.generated Wed Apr 24 10:17:13 CST 2019
     */
    public String getGongfeiZifei() {
        return gongfeiZifei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.gongfei_zifei
     *
     * @param gongfeiZifei the value for student.gongfei_zifei
     *
     * @mbg.generated Wed Apr 24 10:17:13 CST 2019
     */
    public void setGongfeiZifei(String gongfeiZifei) {
        this.gongfeiZifei = gongfeiZifei == null ? null : gongfeiZifei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.zizhusheng
     *
     * @return the value of student.zizhusheng
     *
     * @mbg.generated Wed Apr 24 10:17:13 CST 2019
     */
    public String getZizhusheng() {
        return zizhusheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.zizhusheng
     *
     * @param zizhusheng the value for student.zizhusheng
     *
     * @mbg.generated Wed Apr 24 10:17:13 CST 2019
     */
    public void setZizhusheng(String zizhusheng) {
        this.zizhusheng = zizhusheng == null ? null : zizhusheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.jiandanglikahu
     *
     * @return the value of student.jiandanglikahu
     *
     * @mbg.generated Wed Apr 24 10:17:13 CST 2019
     */
    public String getJiandanglikahu() {
        return jiandanglikahu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.jiandanglikahu
     *
     * @param jiandanglikahu the value for student.jiandanglikahu
     *
     * @mbg.generated Wed Apr 24 10:17:13 CST 2019
     */
    public void setJiandanglikahu(String jiandanglikahu) {
        this.jiandanglikahu = jiandanglikahu == null ? null : jiandanglikahu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.yunxiaoyuan_phone
     *
     * @return the value of student.yunxiaoyuan_phone
     *
     * @mbg.generated Wed Apr 24 10:17:13 CST 2019
     */
    public String getYunxiaoyuanPhone() {
        return yunxiaoyuanPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.yunxiaoyuan_phone
     *
     * @param yunxiaoyuanPhone the value for student.yunxiaoyuan_phone
     *
     * @mbg.generated Wed Apr 24 10:17:13 CST 2019
     */
    public void setYunxiaoyuanPhone(String yunxiaoyuanPhone) {
        this.yunxiaoyuanPhone = yunxiaoyuanPhone == null ? null : yunxiaoyuanPhone.trim();
    }
}