package cn.xvkang.entity;

import java.io.Serializable;

public class Student implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbg.generated Tue Apr 23 17:20:09 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.phone
     *
     * @mbg.generated Tue Apr 23 17:20:09 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbg.generated Tue Apr 23 17:20:09 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.idcard
     *
     * @mbg.generated Tue Apr 23 17:20:09 CST 2019
     */
    private String idcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.select_kemuzuheid
     *
     * @mbg.generated Tue Apr 23 17:20:09 CST 2019
     */
    private Integer selectKemuzuheid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.gender
     *
     * @mbg.generated Tue Apr 23 17:20:09 CST 2019
     */
    private Integer gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.select_kemuzuhe_again
     *
     * @mbg.generated Tue Apr 23 17:20:09 CST 2019
     */
    private Integer selectKemuzuheAgain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student
     *
     * @mbg.generated Tue Apr 23 17:20:09 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbg.generated Tue Apr 23 17:20:09 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbg.generated Tue Apr 23 17:20:09 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.phone
     *
     * @return the value of student.phone
     *
     * @mbg.generated Tue Apr 23 17:20:09 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.phone
     *
     * @param phone the value for student.phone
     *
     * @mbg.generated Tue Apr 23 17:20:09 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @mbg.generated Tue Apr 23 17:20:09 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @mbg.generated Tue Apr 23 17:20:09 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.idcard
     *
     * @return the value of student.idcard
     *
     * @mbg.generated Tue Apr 23 17:20:09 CST 2019
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.idcard
     *
     * @param idcard the value for student.idcard
     *
     * @mbg.generated Tue Apr 23 17:20:09 CST 2019
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.select_kemuzuheid
     *
     * @return the value of student.select_kemuzuheid
     *
     * @mbg.generated Tue Apr 23 17:20:09 CST 2019
     */
    public Integer getSelectKemuzuheid() {
        return selectKemuzuheid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.select_kemuzuheid
     *
     * @param selectKemuzuheid the value for student.select_kemuzuheid
     *
     * @mbg.generated Tue Apr 23 17:20:09 CST 2019
     */
    public void setSelectKemuzuheid(Integer selectKemuzuheid) {
        this.selectKemuzuheid = selectKemuzuheid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.gender
     *
     * @return the value of student.gender
     *
     * @mbg.generated Tue Apr 23 17:20:09 CST 2019
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.gender
     *
     * @param gender the value for student.gender
     *
     * @mbg.generated Tue Apr 23 17:20:09 CST 2019
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.select_kemuzuhe_again
     *
     * @return the value of student.select_kemuzuhe_again
     *
     * @mbg.generated Tue Apr 23 17:20:09 CST 2019
     */
    public Integer getSelectKemuzuheAgain() {
        return selectKemuzuheAgain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.select_kemuzuhe_again
     *
     * @param selectKemuzuheAgain the value for student.select_kemuzuhe_again
     *
     * @mbg.generated Tue Apr 23 17:20:09 CST 2019
     */
    public void setSelectKemuzuheAgain(Integer selectKemuzuheAgain) {
        this.selectKemuzuheAgain = selectKemuzuheAgain;
    }
}