package cn.xvkang.entity;

import java.util.ArrayList;
import java.util.List;

public class StudentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public StudentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table student
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("`name` is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("`name` is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("`name` =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("`name` <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("`name` >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("`name` >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("`name` <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("`name` <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("`name` like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("`name` not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("`name` in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("`name` not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("`name` between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("`name` not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andIdcardIsNull() {
            addCriterion("idcard is null");
            return (Criteria) this;
        }

        public Criteria andIdcardIsNotNull() {
            addCriterion("idcard is not null");
            return (Criteria) this;
        }

        public Criteria andIdcardEqualTo(String value) {
            addCriterion("idcard =", value, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardNotEqualTo(String value) {
            addCriterion("idcard <>", value, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardGreaterThan(String value) {
            addCriterion("idcard >", value, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardGreaterThanOrEqualTo(String value) {
            addCriterion("idcard >=", value, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardLessThan(String value) {
            addCriterion("idcard <", value, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardLessThanOrEqualTo(String value) {
            addCriterion("idcard <=", value, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardLike(String value) {
            addCriterion("idcard like", value, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardNotLike(String value) {
            addCriterion("idcard not like", value, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardIn(List<String> values) {
            addCriterion("idcard in", values, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardNotIn(List<String> values) {
            addCriterion("idcard not in", values, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardBetween(String value1, String value2) {
            addCriterion("idcard between", value1, value2, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardNotBetween(String value1, String value2) {
            addCriterion("idcard not between", value1, value2, "idcard");
            return (Criteria) this;
        }

        public Criteria andSelectKemuzuheidIsNull() {
            addCriterion("select_kemuzuheid is null");
            return (Criteria) this;
        }

        public Criteria andSelectKemuzuheidIsNotNull() {
            addCriterion("select_kemuzuheid is not null");
            return (Criteria) this;
        }

        public Criteria andSelectKemuzuheidEqualTo(Integer value) {
            addCriterion("select_kemuzuheid =", value, "selectKemuzuheid");
            return (Criteria) this;
        }

        public Criteria andSelectKemuzuheidNotEqualTo(Integer value) {
            addCriterion("select_kemuzuheid <>", value, "selectKemuzuheid");
            return (Criteria) this;
        }

        public Criteria andSelectKemuzuheidGreaterThan(Integer value) {
            addCriterion("select_kemuzuheid >", value, "selectKemuzuheid");
            return (Criteria) this;
        }

        public Criteria andSelectKemuzuheidGreaterThanOrEqualTo(Integer value) {
            addCriterion("select_kemuzuheid >=", value, "selectKemuzuheid");
            return (Criteria) this;
        }

        public Criteria andSelectKemuzuheidLessThan(Integer value) {
            addCriterion("select_kemuzuheid <", value, "selectKemuzuheid");
            return (Criteria) this;
        }

        public Criteria andSelectKemuzuheidLessThanOrEqualTo(Integer value) {
            addCriterion("select_kemuzuheid <=", value, "selectKemuzuheid");
            return (Criteria) this;
        }

        public Criteria andSelectKemuzuheidIn(List<Integer> values) {
            addCriterion("select_kemuzuheid in", values, "selectKemuzuheid");
            return (Criteria) this;
        }

        public Criteria andSelectKemuzuheidNotIn(List<Integer> values) {
            addCriterion("select_kemuzuheid not in", values, "selectKemuzuheid");
            return (Criteria) this;
        }

        public Criteria andSelectKemuzuheidBetween(Integer value1, Integer value2) {
            addCriterion("select_kemuzuheid between", value1, value2, "selectKemuzuheid");
            return (Criteria) this;
        }

        public Criteria andSelectKemuzuheidNotBetween(Integer value1, Integer value2) {
            addCriterion("select_kemuzuheid not between", value1, value2, "selectKemuzuheid");
            return (Criteria) this;
        }

        public Criteria andGenderIsNull() {
            addCriterion("gender is null");
            return (Criteria) this;
        }

        public Criteria andGenderIsNotNull() {
            addCriterion("gender is not null");
            return (Criteria) this;
        }

        public Criteria andGenderEqualTo(Integer value) {
            addCriterion("gender =", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotEqualTo(Integer value) {
            addCriterion("gender <>", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThan(Integer value) {
            addCriterion("gender >", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThanOrEqualTo(Integer value) {
            addCriterion("gender >=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThan(Integer value) {
            addCriterion("gender <", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThanOrEqualTo(Integer value) {
            addCriterion("gender <=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderIn(List<Integer> values) {
            addCriterion("gender in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotIn(List<Integer> values) {
            addCriterion("gender not in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderBetween(Integer value1, Integer value2) {
            addCriterion("gender between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotBetween(Integer value1, Integer value2) {
            addCriterion("gender not between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andSelectKemuzuheAgainIsNull() {
            addCriterion("select_kemuzuhe_again is null");
            return (Criteria) this;
        }

        public Criteria andSelectKemuzuheAgainIsNotNull() {
            addCriterion("select_kemuzuhe_again is not null");
            return (Criteria) this;
        }

        public Criteria andSelectKemuzuheAgainEqualTo(Integer value) {
            addCriterion("select_kemuzuhe_again =", value, "selectKemuzuheAgain");
            return (Criteria) this;
        }

        public Criteria andSelectKemuzuheAgainNotEqualTo(Integer value) {
            addCriterion("select_kemuzuhe_again <>", value, "selectKemuzuheAgain");
            return (Criteria) this;
        }

        public Criteria andSelectKemuzuheAgainGreaterThan(Integer value) {
            addCriterion("select_kemuzuhe_again >", value, "selectKemuzuheAgain");
            return (Criteria) this;
        }

        public Criteria andSelectKemuzuheAgainGreaterThanOrEqualTo(Integer value) {
            addCriterion("select_kemuzuhe_again >=", value, "selectKemuzuheAgain");
            return (Criteria) this;
        }

        public Criteria andSelectKemuzuheAgainLessThan(Integer value) {
            addCriterion("select_kemuzuhe_again <", value, "selectKemuzuheAgain");
            return (Criteria) this;
        }

        public Criteria andSelectKemuzuheAgainLessThanOrEqualTo(Integer value) {
            addCriterion("select_kemuzuhe_again <=", value, "selectKemuzuheAgain");
            return (Criteria) this;
        }

        public Criteria andSelectKemuzuheAgainIn(List<Integer> values) {
            addCriterion("select_kemuzuhe_again in", values, "selectKemuzuheAgain");
            return (Criteria) this;
        }

        public Criteria andSelectKemuzuheAgainNotIn(List<Integer> values) {
            addCriterion("select_kemuzuhe_again not in", values, "selectKemuzuheAgain");
            return (Criteria) this;
        }

        public Criteria andSelectKemuzuheAgainBetween(Integer value1, Integer value2) {
            addCriterion("select_kemuzuhe_again between", value1, value2, "selectKemuzuheAgain");
            return (Criteria) this;
        }

        public Criteria andSelectKemuzuheAgainNotBetween(Integer value1, Integer value2) {
            addCriterion("select_kemuzuhe_again not between", value1, value2, "selectKemuzuheAgain");
            return (Criteria) this;
        }

        public Criteria andXuejihaoIsNull() {
            addCriterion("xuejihao is null");
            return (Criteria) this;
        }

        public Criteria andXuejihaoIsNotNull() {
            addCriterion("xuejihao is not null");
            return (Criteria) this;
        }

        public Criteria andXuejihaoEqualTo(String value) {
            addCriterion("xuejihao =", value, "xuejihao");
            return (Criteria) this;
        }

        public Criteria andXuejihaoNotEqualTo(String value) {
            addCriterion("xuejihao <>", value, "xuejihao");
            return (Criteria) this;
        }

        public Criteria andXuejihaoGreaterThan(String value) {
            addCriterion("xuejihao >", value, "xuejihao");
            return (Criteria) this;
        }

        public Criteria andXuejihaoGreaterThanOrEqualTo(String value) {
            addCriterion("xuejihao >=", value, "xuejihao");
            return (Criteria) this;
        }

        public Criteria andXuejihaoLessThan(String value) {
            addCriterion("xuejihao <", value, "xuejihao");
            return (Criteria) this;
        }

        public Criteria andXuejihaoLessThanOrEqualTo(String value) {
            addCriterion("xuejihao <=", value, "xuejihao");
            return (Criteria) this;
        }

        public Criteria andXuejihaoLike(String value) {
            addCriterion("xuejihao like", value, "xuejihao");
            return (Criteria) this;
        }

        public Criteria andXuejihaoNotLike(String value) {
            addCriterion("xuejihao not like", value, "xuejihao");
            return (Criteria) this;
        }

        public Criteria andXuejihaoIn(List<String> values) {
            addCriterion("xuejihao in", values, "xuejihao");
            return (Criteria) this;
        }

        public Criteria andXuejihaoNotIn(List<String> values) {
            addCriterion("xuejihao not in", values, "xuejihao");
            return (Criteria) this;
        }

        public Criteria andXuejihaoBetween(String value1, String value2) {
            addCriterion("xuejihao between", value1, value2, "xuejihao");
            return (Criteria) this;
        }

        public Criteria andXuejihaoNotBetween(String value1, String value2) {
            addCriterion("xuejihao not between", value1, value2, "xuejihao");
            return (Criteria) this;
        }

        public Criteria andNijiNameIsNull() {
            addCriterion("niji_name is null");
            return (Criteria) this;
        }

        public Criteria andNijiNameIsNotNull() {
            addCriterion("niji_name is not null");
            return (Criteria) this;
        }

        public Criteria andNijiNameEqualTo(String value) {
            addCriterion("niji_name =", value, "nijiName");
            return (Criteria) this;
        }

        public Criteria andNijiNameNotEqualTo(String value) {
            addCriterion("niji_name <>", value, "nijiName");
            return (Criteria) this;
        }

        public Criteria andNijiNameGreaterThan(String value) {
            addCriterion("niji_name >", value, "nijiName");
            return (Criteria) this;
        }

        public Criteria andNijiNameGreaterThanOrEqualTo(String value) {
            addCriterion("niji_name >=", value, "nijiName");
            return (Criteria) this;
        }

        public Criteria andNijiNameLessThan(String value) {
            addCriterion("niji_name <", value, "nijiName");
            return (Criteria) this;
        }

        public Criteria andNijiNameLessThanOrEqualTo(String value) {
            addCriterion("niji_name <=", value, "nijiName");
            return (Criteria) this;
        }

        public Criteria andNijiNameLike(String value) {
            addCriterion("niji_name like", value, "nijiName");
            return (Criteria) this;
        }

        public Criteria andNijiNameNotLike(String value) {
            addCriterion("niji_name not like", value, "nijiName");
            return (Criteria) this;
        }

        public Criteria andNijiNameIn(List<String> values) {
            addCriterion("niji_name in", values, "nijiName");
            return (Criteria) this;
        }

        public Criteria andNijiNameNotIn(List<String> values) {
            addCriterion("niji_name not in", values, "nijiName");
            return (Criteria) this;
        }

        public Criteria andNijiNameBetween(String value1, String value2) {
            addCriterion("niji_name between", value1, value2, "nijiName");
            return (Criteria) this;
        }

        public Criteria andNijiNameNotBetween(String value1, String value2) {
            addCriterion("niji_name not between", value1, value2, "nijiName");
            return (Criteria) this;
        }

        public Criteria andBanjiNameIsNull() {
            addCriterion("banji_name is null");
            return (Criteria) this;
        }

        public Criteria andBanjiNameIsNotNull() {
            addCriterion("banji_name is not null");
            return (Criteria) this;
        }

        public Criteria andBanjiNameEqualTo(String value) {
            addCriterion("banji_name =", value, "banjiName");
            return (Criteria) this;
        }

        public Criteria andBanjiNameNotEqualTo(String value) {
            addCriterion("banji_name <>", value, "banjiName");
            return (Criteria) this;
        }

        public Criteria andBanjiNameGreaterThan(String value) {
            addCriterion("banji_name >", value, "banjiName");
            return (Criteria) this;
        }

        public Criteria andBanjiNameGreaterThanOrEqualTo(String value) {
            addCriterion("banji_name >=", value, "banjiName");
            return (Criteria) this;
        }

        public Criteria andBanjiNameLessThan(String value) {
            addCriterion("banji_name <", value, "banjiName");
            return (Criteria) this;
        }

        public Criteria andBanjiNameLessThanOrEqualTo(String value) {
            addCriterion("banji_name <=", value, "banjiName");
            return (Criteria) this;
        }

        public Criteria andBanjiNameLike(String value) {
            addCriterion("banji_name like", value, "banjiName");
            return (Criteria) this;
        }

        public Criteria andBanjiNameNotLike(String value) {
            addCriterion("banji_name not like", value, "banjiName");
            return (Criteria) this;
        }

        public Criteria andBanjiNameIn(List<String> values) {
            addCriterion("banji_name in", values, "banjiName");
            return (Criteria) this;
        }

        public Criteria andBanjiNameNotIn(List<String> values) {
            addCriterion("banji_name not in", values, "banjiName");
            return (Criteria) this;
        }

        public Criteria andBanjiNameBetween(String value1, String value2) {
            addCriterion("banji_name between", value1, value2, "banjiName");
            return (Criteria) this;
        }

        public Criteria andBanjiNameNotBetween(String value1, String value2) {
            addCriterion("banji_name not between", value1, value2, "banjiName");
            return (Criteria) this;
        }

        public Criteria andJibuNameIsNull() {
            addCriterion("jibu_name is null");
            return (Criteria) this;
        }

        public Criteria andJibuNameIsNotNull() {
            addCriterion("jibu_name is not null");
            return (Criteria) this;
        }

        public Criteria andJibuNameEqualTo(String value) {
            addCriterion("jibu_name =", value, "jibuName");
            return (Criteria) this;
        }

        public Criteria andJibuNameNotEqualTo(String value) {
            addCriterion("jibu_name <>", value, "jibuName");
            return (Criteria) this;
        }

        public Criteria andJibuNameGreaterThan(String value) {
            addCriterion("jibu_name >", value, "jibuName");
            return (Criteria) this;
        }

        public Criteria andJibuNameGreaterThanOrEqualTo(String value) {
            addCriterion("jibu_name >=", value, "jibuName");
            return (Criteria) this;
        }

        public Criteria andJibuNameLessThan(String value) {
            addCriterion("jibu_name <", value, "jibuName");
            return (Criteria) this;
        }

        public Criteria andJibuNameLessThanOrEqualTo(String value) {
            addCriterion("jibu_name <=", value, "jibuName");
            return (Criteria) this;
        }

        public Criteria andJibuNameLike(String value) {
            addCriterion("jibu_name like", value, "jibuName");
            return (Criteria) this;
        }

        public Criteria andJibuNameNotLike(String value) {
            addCriterion("jibu_name not like", value, "jibuName");
            return (Criteria) this;
        }

        public Criteria andJibuNameIn(List<String> values) {
            addCriterion("jibu_name in", values, "jibuName");
            return (Criteria) this;
        }

        public Criteria andJibuNameNotIn(List<String> values) {
            addCriterion("jibu_name not in", values, "jibuName");
            return (Criteria) this;
        }

        public Criteria andJibuNameBetween(String value1, String value2) {
            addCriterion("jibu_name between", value1, value2, "jibuName");
            return (Criteria) this;
        }

        public Criteria andJibuNameNotBetween(String value1, String value2) {
            addCriterion("jibu_name not between", value1, value2, "jibuName");
            return (Criteria) this;
        }

        public Criteria andBanjiCodeIsNull() {
            addCriterion("banji_code is null");
            return (Criteria) this;
        }

        public Criteria andBanjiCodeIsNotNull() {
            addCriterion("banji_code is not null");
            return (Criteria) this;
        }

        public Criteria andBanjiCodeEqualTo(String value) {
            addCriterion("banji_code =", value, "banjiCode");
            return (Criteria) this;
        }

        public Criteria andBanjiCodeNotEqualTo(String value) {
            addCriterion("banji_code <>", value, "banjiCode");
            return (Criteria) this;
        }

        public Criteria andBanjiCodeGreaterThan(String value) {
            addCriterion("banji_code >", value, "banjiCode");
            return (Criteria) this;
        }

        public Criteria andBanjiCodeGreaterThanOrEqualTo(String value) {
            addCriterion("banji_code >=", value, "banjiCode");
            return (Criteria) this;
        }

        public Criteria andBanjiCodeLessThan(String value) {
            addCriterion("banji_code <", value, "banjiCode");
            return (Criteria) this;
        }

        public Criteria andBanjiCodeLessThanOrEqualTo(String value) {
            addCriterion("banji_code <=", value, "banjiCode");
            return (Criteria) this;
        }

        public Criteria andBanjiCodeLike(String value) {
            addCriterion("banji_code like", value, "banjiCode");
            return (Criteria) this;
        }

        public Criteria andBanjiCodeNotLike(String value) {
            addCriterion("banji_code not like", value, "banjiCode");
            return (Criteria) this;
        }

        public Criteria andBanjiCodeIn(List<String> values) {
            addCriterion("banji_code in", values, "banjiCode");
            return (Criteria) this;
        }

        public Criteria andBanjiCodeNotIn(List<String> values) {
            addCriterion("banji_code not in", values, "banjiCode");
            return (Criteria) this;
        }

        public Criteria andBanjiCodeBetween(String value1, String value2) {
            addCriterion("banji_code between", value1, value2, "banjiCode");
            return (Criteria) this;
        }

        public Criteria andBanjiCodeNotBetween(String value1, String value2) {
            addCriterion("banji_code not between", value1, value2, "banjiCode");
            return (Criteria) this;
        }

        public Criteria andCurrentAddressIsNull() {
            addCriterion("current_address is null");
            return (Criteria) this;
        }

        public Criteria andCurrentAddressIsNotNull() {
            addCriterion("current_address is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentAddressEqualTo(String value) {
            addCriterion("current_address =", value, "currentAddress");
            return (Criteria) this;
        }

        public Criteria andCurrentAddressNotEqualTo(String value) {
            addCriterion("current_address <>", value, "currentAddress");
            return (Criteria) this;
        }

        public Criteria andCurrentAddressGreaterThan(String value) {
            addCriterion("current_address >", value, "currentAddress");
            return (Criteria) this;
        }

        public Criteria andCurrentAddressGreaterThanOrEqualTo(String value) {
            addCriterion("current_address >=", value, "currentAddress");
            return (Criteria) this;
        }

        public Criteria andCurrentAddressLessThan(String value) {
            addCriterion("current_address <", value, "currentAddress");
            return (Criteria) this;
        }

        public Criteria andCurrentAddressLessThanOrEqualTo(String value) {
            addCriterion("current_address <=", value, "currentAddress");
            return (Criteria) this;
        }

        public Criteria andCurrentAddressLike(String value) {
            addCriterion("current_address like", value, "currentAddress");
            return (Criteria) this;
        }

        public Criteria andCurrentAddressNotLike(String value) {
            addCriterion("current_address not like", value, "currentAddress");
            return (Criteria) this;
        }

        public Criteria andCurrentAddressIn(List<String> values) {
            addCriterion("current_address in", values, "currentAddress");
            return (Criteria) this;
        }

        public Criteria andCurrentAddressNotIn(List<String> values) {
            addCriterion("current_address not in", values, "currentAddress");
            return (Criteria) this;
        }

        public Criteria andCurrentAddressBetween(String value1, String value2) {
            addCriterion("current_address between", value1, value2, "currentAddress");
            return (Criteria) this;
        }

        public Criteria andCurrentAddressNotBetween(String value1, String value2) {
            addCriterion("current_address not between", value1, value2, "currentAddress");
            return (Criteria) this;
        }

        public Criteria andContactAddressIsNull() {
            addCriterion("contact_address is null");
            return (Criteria) this;
        }

        public Criteria andContactAddressIsNotNull() {
            addCriterion("contact_address is not null");
            return (Criteria) this;
        }

        public Criteria andContactAddressEqualTo(String value) {
            addCriterion("contact_address =", value, "contactAddress");
            return (Criteria) this;
        }

        public Criteria andContactAddressNotEqualTo(String value) {
            addCriterion("contact_address <>", value, "contactAddress");
            return (Criteria) this;
        }

        public Criteria andContactAddressGreaterThan(String value) {
            addCriterion("contact_address >", value, "contactAddress");
            return (Criteria) this;
        }

        public Criteria andContactAddressGreaterThanOrEqualTo(String value) {
            addCriterion("contact_address >=", value, "contactAddress");
            return (Criteria) this;
        }

        public Criteria andContactAddressLessThan(String value) {
            addCriterion("contact_address <", value, "contactAddress");
            return (Criteria) this;
        }

        public Criteria andContactAddressLessThanOrEqualTo(String value) {
            addCriterion("contact_address <=", value, "contactAddress");
            return (Criteria) this;
        }

        public Criteria andContactAddressLike(String value) {
            addCriterion("contact_address like", value, "contactAddress");
            return (Criteria) this;
        }

        public Criteria andContactAddressNotLike(String value) {
            addCriterion("contact_address not like", value, "contactAddress");
            return (Criteria) this;
        }

        public Criteria andContactAddressIn(List<String> values) {
            addCriterion("contact_address in", values, "contactAddress");
            return (Criteria) this;
        }

        public Criteria andContactAddressNotIn(List<String> values) {
            addCriterion("contact_address not in", values, "contactAddress");
            return (Criteria) this;
        }

        public Criteria andContactAddressBetween(String value1, String value2) {
            addCriterion("contact_address between", value1, value2, "contactAddress");
            return (Criteria) this;
        }

        public Criteria andContactAddressNotBetween(String value1, String value2) {
            addCriterion("contact_address not between", value1, value2, "contactAddress");
            return (Criteria) this;
        }

        public Criteria andContactTelphoneIsNull() {
            addCriterion("contact_telphone is null");
            return (Criteria) this;
        }

        public Criteria andContactTelphoneIsNotNull() {
            addCriterion("contact_telphone is not null");
            return (Criteria) this;
        }

        public Criteria andContactTelphoneEqualTo(String value) {
            addCriterion("contact_telphone =", value, "contactTelphone");
            return (Criteria) this;
        }

        public Criteria andContactTelphoneNotEqualTo(String value) {
            addCriterion("contact_telphone <>", value, "contactTelphone");
            return (Criteria) this;
        }

        public Criteria andContactTelphoneGreaterThan(String value) {
            addCriterion("contact_telphone >", value, "contactTelphone");
            return (Criteria) this;
        }

        public Criteria andContactTelphoneGreaterThanOrEqualTo(String value) {
            addCriterion("contact_telphone >=", value, "contactTelphone");
            return (Criteria) this;
        }

        public Criteria andContactTelphoneLessThan(String value) {
            addCriterion("contact_telphone <", value, "contactTelphone");
            return (Criteria) this;
        }

        public Criteria andContactTelphoneLessThanOrEqualTo(String value) {
            addCriterion("contact_telphone <=", value, "contactTelphone");
            return (Criteria) this;
        }

        public Criteria andContactTelphoneLike(String value) {
            addCriterion("contact_telphone like", value, "contactTelphone");
            return (Criteria) this;
        }

        public Criteria andContactTelphoneNotLike(String value) {
            addCriterion("contact_telphone not like", value, "contactTelphone");
            return (Criteria) this;
        }

        public Criteria andContactTelphoneIn(List<String> values) {
            addCriterion("contact_telphone in", values, "contactTelphone");
            return (Criteria) this;
        }

        public Criteria andContactTelphoneNotIn(List<String> values) {
            addCriterion("contact_telphone not in", values, "contactTelphone");
            return (Criteria) this;
        }

        public Criteria andContactTelphoneBetween(String value1, String value2) {
            addCriterion("contact_telphone between", value1, value2, "contactTelphone");
            return (Criteria) this;
        }

        public Criteria andContactTelphoneNotBetween(String value1, String value2) {
            addCriterion("contact_telphone not between", value1, value2, "contactTelphone");
            return (Criteria) this;
        }

        public Criteria andHomeAddressIsNull() {
            addCriterion("home_address is null");
            return (Criteria) this;
        }

        public Criteria andHomeAddressIsNotNull() {
            addCriterion("home_address is not null");
            return (Criteria) this;
        }

        public Criteria andHomeAddressEqualTo(String value) {
            addCriterion("home_address =", value, "homeAddress");
            return (Criteria) this;
        }

        public Criteria andHomeAddressNotEqualTo(String value) {
            addCriterion("home_address <>", value, "homeAddress");
            return (Criteria) this;
        }

        public Criteria andHomeAddressGreaterThan(String value) {
            addCriterion("home_address >", value, "homeAddress");
            return (Criteria) this;
        }

        public Criteria andHomeAddressGreaterThanOrEqualTo(String value) {
            addCriterion("home_address >=", value, "homeAddress");
            return (Criteria) this;
        }

        public Criteria andHomeAddressLessThan(String value) {
            addCriterion("home_address <", value, "homeAddress");
            return (Criteria) this;
        }

        public Criteria andHomeAddressLessThanOrEqualTo(String value) {
            addCriterion("home_address <=", value, "homeAddress");
            return (Criteria) this;
        }

        public Criteria andHomeAddressLike(String value) {
            addCriterion("home_address like", value, "homeAddress");
            return (Criteria) this;
        }

        public Criteria andHomeAddressNotLike(String value) {
            addCriterion("home_address not like", value, "homeAddress");
            return (Criteria) this;
        }

        public Criteria andHomeAddressIn(List<String> values) {
            addCriterion("home_address in", values, "homeAddress");
            return (Criteria) this;
        }

        public Criteria andHomeAddressNotIn(List<String> values) {
            addCriterion("home_address not in", values, "homeAddress");
            return (Criteria) this;
        }

        public Criteria andHomeAddressBetween(String value1, String value2) {
            addCriterion("home_address between", value1, value2, "homeAddress");
            return (Criteria) this;
        }

        public Criteria andHomeAddressNotBetween(String value1, String value2) {
            addCriterion("home_address not between", value1, value2, "homeAddress");
            return (Criteria) this;
        }

        public Criteria andFatherPhoneIsNull() {
            addCriterion("father_phone is null");
            return (Criteria) this;
        }

        public Criteria andFatherPhoneIsNotNull() {
            addCriterion("father_phone is not null");
            return (Criteria) this;
        }

        public Criteria andFatherPhoneEqualTo(String value) {
            addCriterion("father_phone =", value, "fatherPhone");
            return (Criteria) this;
        }

        public Criteria andFatherPhoneNotEqualTo(String value) {
            addCriterion("father_phone <>", value, "fatherPhone");
            return (Criteria) this;
        }

        public Criteria andFatherPhoneGreaterThan(String value) {
            addCriterion("father_phone >", value, "fatherPhone");
            return (Criteria) this;
        }

        public Criteria andFatherPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("father_phone >=", value, "fatherPhone");
            return (Criteria) this;
        }

        public Criteria andFatherPhoneLessThan(String value) {
            addCriterion("father_phone <", value, "fatherPhone");
            return (Criteria) this;
        }

        public Criteria andFatherPhoneLessThanOrEqualTo(String value) {
            addCriterion("father_phone <=", value, "fatherPhone");
            return (Criteria) this;
        }

        public Criteria andFatherPhoneLike(String value) {
            addCriterion("father_phone like", value, "fatherPhone");
            return (Criteria) this;
        }

        public Criteria andFatherPhoneNotLike(String value) {
            addCriterion("father_phone not like", value, "fatherPhone");
            return (Criteria) this;
        }

        public Criteria andFatherPhoneIn(List<String> values) {
            addCriterion("father_phone in", values, "fatherPhone");
            return (Criteria) this;
        }

        public Criteria andFatherPhoneNotIn(List<String> values) {
            addCriterion("father_phone not in", values, "fatherPhone");
            return (Criteria) this;
        }

        public Criteria andFatherPhoneBetween(String value1, String value2) {
            addCriterion("father_phone between", value1, value2, "fatherPhone");
            return (Criteria) this;
        }

        public Criteria andFatherPhoneNotBetween(String value1, String value2) {
            addCriterion("father_phone not between", value1, value2, "fatherPhone");
            return (Criteria) this;
        }

        public Criteria andMotherPhoneIsNull() {
            addCriterion("mother_phone is null");
            return (Criteria) this;
        }

        public Criteria andMotherPhoneIsNotNull() {
            addCriterion("mother_phone is not null");
            return (Criteria) this;
        }

        public Criteria andMotherPhoneEqualTo(String value) {
            addCriterion("mother_phone =", value, "motherPhone");
            return (Criteria) this;
        }

        public Criteria andMotherPhoneNotEqualTo(String value) {
            addCriterion("mother_phone <>", value, "motherPhone");
            return (Criteria) this;
        }

        public Criteria andMotherPhoneGreaterThan(String value) {
            addCriterion("mother_phone >", value, "motherPhone");
            return (Criteria) this;
        }

        public Criteria andMotherPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("mother_phone >=", value, "motherPhone");
            return (Criteria) this;
        }

        public Criteria andMotherPhoneLessThan(String value) {
            addCriterion("mother_phone <", value, "motherPhone");
            return (Criteria) this;
        }

        public Criteria andMotherPhoneLessThanOrEqualTo(String value) {
            addCriterion("mother_phone <=", value, "motherPhone");
            return (Criteria) this;
        }

        public Criteria andMotherPhoneLike(String value) {
            addCriterion("mother_phone like", value, "motherPhone");
            return (Criteria) this;
        }

        public Criteria andMotherPhoneNotLike(String value) {
            addCriterion("mother_phone not like", value, "motherPhone");
            return (Criteria) this;
        }

        public Criteria andMotherPhoneIn(List<String> values) {
            addCriterion("mother_phone in", values, "motherPhone");
            return (Criteria) this;
        }

        public Criteria andMotherPhoneNotIn(List<String> values) {
            addCriterion("mother_phone not in", values, "motherPhone");
            return (Criteria) this;
        }

        public Criteria andMotherPhoneBetween(String value1, String value2) {
            addCriterion("mother_phone between", value1, value2, "motherPhone");
            return (Criteria) this;
        }

        public Criteria andMotherPhoneNotBetween(String value1, String value2) {
            addCriterion("mother_phone not between", value1, value2, "motherPhone");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanNameIsNull() {
            addCriterion("yunxiaoyuan_name is null");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanNameIsNotNull() {
            addCriterion("yunxiaoyuan_name is not null");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanNameEqualTo(String value) {
            addCriterion("yunxiaoyuan_name =", value, "yunxiaoyuanName");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanNameNotEqualTo(String value) {
            addCriterion("yunxiaoyuan_name <>", value, "yunxiaoyuanName");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanNameGreaterThan(String value) {
            addCriterion("yunxiaoyuan_name >", value, "yunxiaoyuanName");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanNameGreaterThanOrEqualTo(String value) {
            addCriterion("yunxiaoyuan_name >=", value, "yunxiaoyuanName");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanNameLessThan(String value) {
            addCriterion("yunxiaoyuan_name <", value, "yunxiaoyuanName");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanNameLessThanOrEqualTo(String value) {
            addCriterion("yunxiaoyuan_name <=", value, "yunxiaoyuanName");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanNameLike(String value) {
            addCriterion("yunxiaoyuan_name like", value, "yunxiaoyuanName");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanNameNotLike(String value) {
            addCriterion("yunxiaoyuan_name not like", value, "yunxiaoyuanName");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanNameIn(List<String> values) {
            addCriterion("yunxiaoyuan_name in", values, "yunxiaoyuanName");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanNameNotIn(List<String> values) {
            addCriterion("yunxiaoyuan_name not in", values, "yunxiaoyuanName");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanNameBetween(String value1, String value2) {
            addCriterion("yunxiaoyuan_name between", value1, value2, "yunxiaoyuanName");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanNameNotBetween(String value1, String value2) {
            addCriterion("yunxiaoyuan_name not between", value1, value2, "yunxiaoyuanName");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanBanjicodeIsNull() {
            addCriterion("yunxiaoyuan_banjicode is null");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanBanjicodeIsNotNull() {
            addCriterion("yunxiaoyuan_banjicode is not null");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanBanjicodeEqualTo(String value) {
            addCriterion("yunxiaoyuan_banjicode =", value, "yunxiaoyuanBanjicode");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanBanjicodeNotEqualTo(String value) {
            addCriterion("yunxiaoyuan_banjicode <>", value, "yunxiaoyuanBanjicode");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanBanjicodeGreaterThan(String value) {
            addCriterion("yunxiaoyuan_banjicode >", value, "yunxiaoyuanBanjicode");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanBanjicodeGreaterThanOrEqualTo(String value) {
            addCriterion("yunxiaoyuan_banjicode >=", value, "yunxiaoyuanBanjicode");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanBanjicodeLessThan(String value) {
            addCriterion("yunxiaoyuan_banjicode <", value, "yunxiaoyuanBanjicode");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanBanjicodeLessThanOrEqualTo(String value) {
            addCriterion("yunxiaoyuan_banjicode <=", value, "yunxiaoyuanBanjicode");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanBanjicodeLike(String value) {
            addCriterion("yunxiaoyuan_banjicode like", value, "yunxiaoyuanBanjicode");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanBanjicodeNotLike(String value) {
            addCriterion("yunxiaoyuan_banjicode not like", value, "yunxiaoyuanBanjicode");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanBanjicodeIn(List<String> values) {
            addCriterion("yunxiaoyuan_banjicode in", values, "yunxiaoyuanBanjicode");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanBanjicodeNotIn(List<String> values) {
            addCriterion("yunxiaoyuan_banjicode not in", values, "yunxiaoyuanBanjicode");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanBanjicodeBetween(String value1, String value2) {
            addCriterion("yunxiaoyuan_banjicode between", value1, value2, "yunxiaoyuanBanjicode");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanBanjicodeNotBetween(String value1, String value2) {
            addCriterion("yunxiaoyuan_banjicode not between", value1, value2, "yunxiaoyuanBanjicode");
            return (Criteria) this;
        }

        public Criteria andUniqueCodeIsNull() {
            addCriterion("unique_code is null");
            return (Criteria) this;
        }

        public Criteria andUniqueCodeIsNotNull() {
            addCriterion("unique_code is not null");
            return (Criteria) this;
        }

        public Criteria andUniqueCodeEqualTo(String value) {
            addCriterion("unique_code =", value, "uniqueCode");
            return (Criteria) this;
        }

        public Criteria andUniqueCodeNotEqualTo(String value) {
            addCriterion("unique_code <>", value, "uniqueCode");
            return (Criteria) this;
        }

        public Criteria andUniqueCodeGreaterThan(String value) {
            addCriterion("unique_code >", value, "uniqueCode");
            return (Criteria) this;
        }

        public Criteria andUniqueCodeGreaterThanOrEqualTo(String value) {
            addCriterion("unique_code >=", value, "uniqueCode");
            return (Criteria) this;
        }

        public Criteria andUniqueCodeLessThan(String value) {
            addCriterion("unique_code <", value, "uniqueCode");
            return (Criteria) this;
        }

        public Criteria andUniqueCodeLessThanOrEqualTo(String value) {
            addCriterion("unique_code <=", value, "uniqueCode");
            return (Criteria) this;
        }

        public Criteria andUniqueCodeLike(String value) {
            addCriterion("unique_code like", value, "uniqueCode");
            return (Criteria) this;
        }

        public Criteria andUniqueCodeNotLike(String value) {
            addCriterion("unique_code not like", value, "uniqueCode");
            return (Criteria) this;
        }

        public Criteria andUniqueCodeIn(List<String> values) {
            addCriterion("unique_code in", values, "uniqueCode");
            return (Criteria) this;
        }

        public Criteria andUniqueCodeNotIn(List<String> values) {
            addCriterion("unique_code not in", values, "uniqueCode");
            return (Criteria) this;
        }

        public Criteria andUniqueCodeBetween(String value1, String value2) {
            addCriterion("unique_code between", value1, value2, "uniqueCode");
            return (Criteria) this;
        }

        public Criteria andUniqueCodeNotBetween(String value1, String value2) {
            addCriterion("unique_code not between", value1, value2, "uniqueCode");
            return (Criteria) this;
        }

        public Criteria andGongfeiZifeiIsNull() {
            addCriterion("gongfei_zifei is null");
            return (Criteria) this;
        }

        public Criteria andGongfeiZifeiIsNotNull() {
            addCriterion("gongfei_zifei is not null");
            return (Criteria) this;
        }

        public Criteria andGongfeiZifeiEqualTo(String value) {
            addCriterion("gongfei_zifei =", value, "gongfeiZifei");
            return (Criteria) this;
        }

        public Criteria andGongfeiZifeiNotEqualTo(String value) {
            addCriterion("gongfei_zifei <>", value, "gongfeiZifei");
            return (Criteria) this;
        }

        public Criteria andGongfeiZifeiGreaterThan(String value) {
            addCriterion("gongfei_zifei >", value, "gongfeiZifei");
            return (Criteria) this;
        }

        public Criteria andGongfeiZifeiGreaterThanOrEqualTo(String value) {
            addCriterion("gongfei_zifei >=", value, "gongfeiZifei");
            return (Criteria) this;
        }

        public Criteria andGongfeiZifeiLessThan(String value) {
            addCriterion("gongfei_zifei <", value, "gongfeiZifei");
            return (Criteria) this;
        }

        public Criteria andGongfeiZifeiLessThanOrEqualTo(String value) {
            addCriterion("gongfei_zifei <=", value, "gongfeiZifei");
            return (Criteria) this;
        }

        public Criteria andGongfeiZifeiLike(String value) {
            addCriterion("gongfei_zifei like", value, "gongfeiZifei");
            return (Criteria) this;
        }

        public Criteria andGongfeiZifeiNotLike(String value) {
            addCriterion("gongfei_zifei not like", value, "gongfeiZifei");
            return (Criteria) this;
        }

        public Criteria andGongfeiZifeiIn(List<String> values) {
            addCriterion("gongfei_zifei in", values, "gongfeiZifei");
            return (Criteria) this;
        }

        public Criteria andGongfeiZifeiNotIn(List<String> values) {
            addCriterion("gongfei_zifei not in", values, "gongfeiZifei");
            return (Criteria) this;
        }

        public Criteria andGongfeiZifeiBetween(String value1, String value2) {
            addCriterion("gongfei_zifei between", value1, value2, "gongfeiZifei");
            return (Criteria) this;
        }

        public Criteria andGongfeiZifeiNotBetween(String value1, String value2) {
            addCriterion("gongfei_zifei not between", value1, value2, "gongfeiZifei");
            return (Criteria) this;
        }

        public Criteria andZizhushengIsNull() {
            addCriterion("zizhusheng is null");
            return (Criteria) this;
        }

        public Criteria andZizhushengIsNotNull() {
            addCriterion("zizhusheng is not null");
            return (Criteria) this;
        }

        public Criteria andZizhushengEqualTo(String value) {
            addCriterion("zizhusheng =", value, "zizhusheng");
            return (Criteria) this;
        }

        public Criteria andZizhushengNotEqualTo(String value) {
            addCriterion("zizhusheng <>", value, "zizhusheng");
            return (Criteria) this;
        }

        public Criteria andZizhushengGreaterThan(String value) {
            addCriterion("zizhusheng >", value, "zizhusheng");
            return (Criteria) this;
        }

        public Criteria andZizhushengGreaterThanOrEqualTo(String value) {
            addCriterion("zizhusheng >=", value, "zizhusheng");
            return (Criteria) this;
        }

        public Criteria andZizhushengLessThan(String value) {
            addCriterion("zizhusheng <", value, "zizhusheng");
            return (Criteria) this;
        }

        public Criteria andZizhushengLessThanOrEqualTo(String value) {
            addCriterion("zizhusheng <=", value, "zizhusheng");
            return (Criteria) this;
        }

        public Criteria andZizhushengLike(String value) {
            addCriterion("zizhusheng like", value, "zizhusheng");
            return (Criteria) this;
        }

        public Criteria andZizhushengNotLike(String value) {
            addCriterion("zizhusheng not like", value, "zizhusheng");
            return (Criteria) this;
        }

        public Criteria andZizhushengIn(List<String> values) {
            addCriterion("zizhusheng in", values, "zizhusheng");
            return (Criteria) this;
        }

        public Criteria andZizhushengNotIn(List<String> values) {
            addCriterion("zizhusheng not in", values, "zizhusheng");
            return (Criteria) this;
        }

        public Criteria andZizhushengBetween(String value1, String value2) {
            addCriterion("zizhusheng between", value1, value2, "zizhusheng");
            return (Criteria) this;
        }

        public Criteria andZizhushengNotBetween(String value1, String value2) {
            addCriterion("zizhusheng not between", value1, value2, "zizhusheng");
            return (Criteria) this;
        }

        public Criteria andJiandanglikahuIsNull() {
            addCriterion("jiandanglikahu is null");
            return (Criteria) this;
        }

        public Criteria andJiandanglikahuIsNotNull() {
            addCriterion("jiandanglikahu is not null");
            return (Criteria) this;
        }

        public Criteria andJiandanglikahuEqualTo(String value) {
            addCriterion("jiandanglikahu =", value, "jiandanglikahu");
            return (Criteria) this;
        }

        public Criteria andJiandanglikahuNotEqualTo(String value) {
            addCriterion("jiandanglikahu <>", value, "jiandanglikahu");
            return (Criteria) this;
        }

        public Criteria andJiandanglikahuGreaterThan(String value) {
            addCriterion("jiandanglikahu >", value, "jiandanglikahu");
            return (Criteria) this;
        }

        public Criteria andJiandanglikahuGreaterThanOrEqualTo(String value) {
            addCriterion("jiandanglikahu >=", value, "jiandanglikahu");
            return (Criteria) this;
        }

        public Criteria andJiandanglikahuLessThan(String value) {
            addCriterion("jiandanglikahu <", value, "jiandanglikahu");
            return (Criteria) this;
        }

        public Criteria andJiandanglikahuLessThanOrEqualTo(String value) {
            addCriterion("jiandanglikahu <=", value, "jiandanglikahu");
            return (Criteria) this;
        }

        public Criteria andJiandanglikahuLike(String value) {
            addCriterion("jiandanglikahu like", value, "jiandanglikahu");
            return (Criteria) this;
        }

        public Criteria andJiandanglikahuNotLike(String value) {
            addCriterion("jiandanglikahu not like", value, "jiandanglikahu");
            return (Criteria) this;
        }

        public Criteria andJiandanglikahuIn(List<String> values) {
            addCriterion("jiandanglikahu in", values, "jiandanglikahu");
            return (Criteria) this;
        }

        public Criteria andJiandanglikahuNotIn(List<String> values) {
            addCriterion("jiandanglikahu not in", values, "jiandanglikahu");
            return (Criteria) this;
        }

        public Criteria andJiandanglikahuBetween(String value1, String value2) {
            addCriterion("jiandanglikahu between", value1, value2, "jiandanglikahu");
            return (Criteria) this;
        }

        public Criteria andJiandanglikahuNotBetween(String value1, String value2) {
            addCriterion("jiandanglikahu not between", value1, value2, "jiandanglikahu");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanPhoneIsNull() {
            addCriterion("yunxiaoyuan_phone is null");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanPhoneIsNotNull() {
            addCriterion("yunxiaoyuan_phone is not null");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanPhoneEqualTo(String value) {
            addCriterion("yunxiaoyuan_phone =", value, "yunxiaoyuanPhone");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanPhoneNotEqualTo(String value) {
            addCriterion("yunxiaoyuan_phone <>", value, "yunxiaoyuanPhone");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanPhoneGreaterThan(String value) {
            addCriterion("yunxiaoyuan_phone >", value, "yunxiaoyuanPhone");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("yunxiaoyuan_phone >=", value, "yunxiaoyuanPhone");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanPhoneLessThan(String value) {
            addCriterion("yunxiaoyuan_phone <", value, "yunxiaoyuanPhone");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanPhoneLessThanOrEqualTo(String value) {
            addCriterion("yunxiaoyuan_phone <=", value, "yunxiaoyuanPhone");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanPhoneLike(String value) {
            addCriterion("yunxiaoyuan_phone like", value, "yunxiaoyuanPhone");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanPhoneNotLike(String value) {
            addCriterion("yunxiaoyuan_phone not like", value, "yunxiaoyuanPhone");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanPhoneIn(List<String> values) {
            addCriterion("yunxiaoyuan_phone in", values, "yunxiaoyuanPhone");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanPhoneNotIn(List<String> values) {
            addCriterion("yunxiaoyuan_phone not in", values, "yunxiaoyuanPhone");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanPhoneBetween(String value1, String value2) {
            addCriterion("yunxiaoyuan_phone between", value1, value2, "yunxiaoyuanPhone");
            return (Criteria) this;
        }

        public Criteria andYunxiaoyuanPhoneNotBetween(String value1, String value2) {
            addCriterion("yunxiaoyuan_phone not between", value1, value2, "yunxiaoyuanPhone");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table student
     *
     * @mbg.generated do_not_delete_during_merge Wed Apr 24 10:17:12 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table student
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}