package cn.xvkang.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TXmsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_xms
     *
     * @mbg.generated Fri Apr 12 21:17:04 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_xms
     *
     * @mbg.generated Fri Apr 12 21:17:04 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_xms
     *
     * @mbg.generated Fri Apr 12 21:17:04 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_xms
     *
     * @mbg.generated Fri Apr 12 21:17:04 CST 2019
     */
    public TXmsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_xms
     *
     * @mbg.generated Fri Apr 12 21:17:04 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_xms
     *
     * @mbg.generated Fri Apr 12 21:17:04 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_xms
     *
     * @mbg.generated Fri Apr 12 21:17:04 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_xms
     *
     * @mbg.generated Fri Apr 12 21:17:04 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_xms
     *
     * @mbg.generated Fri Apr 12 21:17:04 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_xms
     *
     * @mbg.generated Fri Apr 12 21:17:04 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_xms
     *
     * @mbg.generated Fri Apr 12 21:17:04 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_xms
     *
     * @mbg.generated Fri Apr 12 21:17:04 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_xms
     *
     * @mbg.generated Fri Apr 12 21:17:04 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_xms
     *
     * @mbg.generated Fri Apr 12 21:17:04 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_xms
     *
     * @mbg.generated Fri Apr 12 21:17:04 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andXmidIsNull() {
            addCriterion("xmid is null");
            return (Criteria) this;
        }

        public Criteria andXmidIsNotNull() {
            addCriterion("xmid is not null");
            return (Criteria) this;
        }

        public Criteria andXmidEqualTo(String value) {
            addCriterion("xmid =", value, "xmid");
            return (Criteria) this;
        }

        public Criteria andXmidNotEqualTo(String value) {
            addCriterion("xmid <>", value, "xmid");
            return (Criteria) this;
        }

        public Criteria andXmidGreaterThan(String value) {
            addCriterion("xmid >", value, "xmid");
            return (Criteria) this;
        }

        public Criteria andXmidGreaterThanOrEqualTo(String value) {
            addCriterion("xmid >=", value, "xmid");
            return (Criteria) this;
        }

        public Criteria andXmidLessThan(String value) {
            addCriterion("xmid <", value, "xmid");
            return (Criteria) this;
        }

        public Criteria andXmidLessThanOrEqualTo(String value) {
            addCriterion("xmid <=", value, "xmid");
            return (Criteria) this;
        }

        public Criteria andXmidLike(String value) {
            addCriterion("xmid like", value, "xmid");
            return (Criteria) this;
        }

        public Criteria andXmidNotLike(String value) {
            addCriterion("xmid not like", value, "xmid");
            return (Criteria) this;
        }

        public Criteria andXmidIn(List<String> values) {
            addCriterion("xmid in", values, "xmid");
            return (Criteria) this;
        }

        public Criteria andXmidNotIn(List<String> values) {
            addCriterion("xmid not in", values, "xmid");
            return (Criteria) this;
        }

        public Criteria andXmidBetween(String value1, String value2) {
            addCriterion("xmid between", value1, value2, "xmid");
            return (Criteria) this;
        }

        public Criteria andXmidNotBetween(String value1, String value2) {
            addCriterion("xmid not between", value1, value2, "xmid");
            return (Criteria) this;
        }

        public Criteria andXmIsNull() {
            addCriterion("xm is null");
            return (Criteria) this;
        }

        public Criteria andXmIsNotNull() {
            addCriterion("xm is not null");
            return (Criteria) this;
        }

        public Criteria andXmEqualTo(String value) {
            addCriterion("xm =", value, "xm");
            return (Criteria) this;
        }

        public Criteria andXmNotEqualTo(String value) {
            addCriterion("xm <>", value, "xm");
            return (Criteria) this;
        }

        public Criteria andXmGreaterThan(String value) {
            addCriterion("xm >", value, "xm");
            return (Criteria) this;
        }

        public Criteria andXmGreaterThanOrEqualTo(String value) {
            addCriterion("xm >=", value, "xm");
            return (Criteria) this;
        }

        public Criteria andXmLessThan(String value) {
            addCriterion("xm <", value, "xm");
            return (Criteria) this;
        }

        public Criteria andXmLessThanOrEqualTo(String value) {
            addCriterion("xm <=", value, "xm");
            return (Criteria) this;
        }

        public Criteria andXmLike(String value) {
            addCriterion("xm like", value, "xm");
            return (Criteria) this;
        }

        public Criteria andXmNotLike(String value) {
            addCriterion("xm not like", value, "xm");
            return (Criteria) this;
        }

        public Criteria andXmIn(List<String> values) {
            addCriterion("xm in", values, "xm");
            return (Criteria) this;
        }

        public Criteria andXmNotIn(List<String> values) {
            addCriterion("xm not in", values, "xm");
            return (Criteria) this;
        }

        public Criteria andXmBetween(String value1, String value2) {
            addCriterion("xm between", value1, value2, "xm");
            return (Criteria) this;
        }

        public Criteria andXmNotBetween(String value1, String value2) {
            addCriterion("xm not between", value1, value2, "xm");
            return (Criteria) this;
        }

        public Criteria andAcyearIsNull() {
            addCriterion("acyear is null");
            return (Criteria) this;
        }

        public Criteria andAcyearIsNotNull() {
            addCriterion("acyear is not null");
            return (Criteria) this;
        }

        public Criteria andAcyearEqualTo(String value) {
            addCriterion("acyear =", value, "acyear");
            return (Criteria) this;
        }

        public Criteria andAcyearNotEqualTo(String value) {
            addCriterion("acyear <>", value, "acyear");
            return (Criteria) this;
        }

        public Criteria andAcyearGreaterThan(String value) {
            addCriterion("acyear >", value, "acyear");
            return (Criteria) this;
        }

        public Criteria andAcyearGreaterThanOrEqualTo(String value) {
            addCriterion("acyear >=", value, "acyear");
            return (Criteria) this;
        }

        public Criteria andAcyearLessThan(String value) {
            addCriterion("acyear <", value, "acyear");
            return (Criteria) this;
        }

        public Criteria andAcyearLessThanOrEqualTo(String value) {
            addCriterion("acyear <=", value, "acyear");
            return (Criteria) this;
        }

        public Criteria andAcyearLike(String value) {
            addCriterion("acyear like", value, "acyear");
            return (Criteria) this;
        }

        public Criteria andAcyearNotLike(String value) {
            addCriterion("acyear not like", value, "acyear");
            return (Criteria) this;
        }

        public Criteria andAcyearIn(List<String> values) {
            addCriterion("acyear in", values, "acyear");
            return (Criteria) this;
        }

        public Criteria andAcyearNotIn(List<String> values) {
            addCriterion("acyear not in", values, "acyear");
            return (Criteria) this;
        }

        public Criteria andAcyearBetween(String value1, String value2) {
            addCriterion("acyear between", value1, value2, "acyear");
            return (Criteria) this;
        }

        public Criteria andAcyearNotBetween(String value1, String value2) {
            addCriterion("acyear not between", value1, value2, "acyear");
            return (Criteria) this;
        }

        public Criteria andCurtimeIsNull() {
            addCriterion("curtime is null");
            return (Criteria) this;
        }

        public Criteria andCurtimeIsNotNull() {
            addCriterion("curtime is not null");
            return (Criteria) this;
        }

        public Criteria andCurtimeEqualTo(Date value) {
            addCriterion("curtime =", value, "curtime");
            return (Criteria) this;
        }

        public Criteria andCurtimeNotEqualTo(Date value) {
            addCriterion("curtime <>", value, "curtime");
            return (Criteria) this;
        }

        public Criteria andCurtimeGreaterThan(Date value) {
            addCriterion("curtime >", value, "curtime");
            return (Criteria) this;
        }

        public Criteria andCurtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("curtime >=", value, "curtime");
            return (Criteria) this;
        }

        public Criteria andCurtimeLessThan(Date value) {
            addCriterion("curtime <", value, "curtime");
            return (Criteria) this;
        }

        public Criteria andCurtimeLessThanOrEqualTo(Date value) {
            addCriterion("curtime <=", value, "curtime");
            return (Criteria) this;
        }

        public Criteria andCurtimeIn(List<Date> values) {
            addCriterion("curtime in", values, "curtime");
            return (Criteria) this;
        }

        public Criteria andCurtimeNotIn(List<Date> values) {
            addCriterion("curtime not in", values, "curtime");
            return (Criteria) this;
        }

        public Criteria andCurtimeBetween(Date value1, Date value2) {
            addCriterion("curtime between", value1, value2, "curtime");
            return (Criteria) this;
        }

        public Criteria andCurtimeNotBetween(Date value1, Date value2) {
            addCriterion("curtime not between", value1, value2, "curtime");
            return (Criteria) this;
        }

        public Criteria andGradeIsNull() {
            addCriterion("grade is null");
            return (Criteria) this;
        }

        public Criteria andGradeIsNotNull() {
            addCriterion("grade is not null");
            return (Criteria) this;
        }

        public Criteria andGradeEqualTo(String value) {
            addCriterion("grade =", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotEqualTo(String value) {
            addCriterion("grade <>", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeGreaterThan(String value) {
            addCriterion("grade >", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeGreaterThanOrEqualTo(String value) {
            addCriterion("grade >=", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLessThan(String value) {
            addCriterion("grade <", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLessThanOrEqualTo(String value) {
            addCriterion("grade <=", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLike(String value) {
            addCriterion("grade like", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotLike(String value) {
            addCriterion("grade not like", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeIn(List<String> values) {
            addCriterion("grade in", values, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotIn(List<String> values) {
            addCriterion("grade not in", values, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeBetween(String value1, String value2) {
            addCriterion("grade between", value1, value2, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotBetween(String value1, String value2) {
            addCriterion("grade not between", value1, value2, "grade");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_xms
     *
     * @mbg.generated do_not_delete_during_merge Fri Apr 12 21:17:04 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_xms
     *
     * @mbg.generated Fri Apr 12 21:17:04 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}