package cn.xvkang.entity;

import java.util.Date;

public class TXms {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_xms.xmid
     *
     * @mbg.generated Fri Apr 12 21:17:04 CST 2019
     */
    private String xmid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_xms.xm
     *
     * @mbg.generated Fri Apr 12 21:17:04 CST 2019
     */
    private String xm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_xms.acyear
     *
     * @mbg.generated Fri Apr 12 21:17:04 CST 2019
     */
    private String acyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_xms.curtime
     *
     * @mbg.generated Fri Apr 12 21:17:04 CST 2019
     */
    private Date curtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_xms.grade
     *
     * @mbg.generated Fri Apr 12 21:17:04 CST 2019
     */
    private String grade;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_xms.xmid
     *
     * @return the value of T_xms.xmid
     *
     * @mbg.generated Fri Apr 12 21:17:04 CST 2019
     */
    public String getXmid() {
        return xmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_xms.xmid
     *
     * @param xmid the value for T_xms.xmid
     *
     * @mbg.generated Fri Apr 12 21:17:04 CST 2019
     */
    public void setXmid(String xmid) {
        this.xmid = xmid == null ? null : xmid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_xms.xm
     *
     * @return the value of T_xms.xm
     *
     * @mbg.generated Fri Apr 12 21:17:04 CST 2019
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_xms.xm
     *
     * @param xm the value for T_xms.xm
     *
     * @mbg.generated Fri Apr 12 21:17:04 CST 2019
     */
    public void setXm(String xm) {
        this.xm = xm == null ? null : xm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_xms.acyear
     *
     * @return the value of T_xms.acyear
     *
     * @mbg.generated Fri Apr 12 21:17:04 CST 2019
     */
    public String getAcyear() {
        return acyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_xms.acyear
     *
     * @param acyear the value for T_xms.acyear
     *
     * @mbg.generated Fri Apr 12 21:17:04 CST 2019
     */
    public void setAcyear(String acyear) {
        this.acyear = acyear == null ? null : acyear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_xms.curtime
     *
     * @return the value of T_xms.curtime
     *
     * @mbg.generated Fri Apr 12 21:17:04 CST 2019
     */
    public Date getCurtime() {
        return curtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_xms.curtime
     *
     * @param curtime the value for T_xms.curtime
     *
     * @mbg.generated Fri Apr 12 21:17:04 CST 2019
     */
    public void setCurtime(Date curtime) {
        this.curtime = curtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_xms.grade
     *
     * @return the value of T_xms.grade
     *
     * @mbg.generated Fri Apr 12 21:17:04 CST 2019
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_xms.grade
     *
     * @param grade the value for T_xms.grade
     *
     * @mbg.generated Fri Apr 12 21:17:04 CST 2019
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }
}