package cn.xvkang.dao;

import cn.xvkang.entity.Kemuzuhe;
import cn.xvkang.entity.KemuzuheExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KemuzuheMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kemuzuhe
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    long countByExample(KemuzuheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kemuzuhe
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    int deleteByExample(KemuzuheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kemuzuhe
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kemuzuhe
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    int insert(Kemuzuhe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kemuzuhe
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    int insertSelective(Kemuzuhe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kemuzuhe
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    List<Kemuzuhe> selectByExample(KemuzuheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kemuzuhe
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    Kemuzuhe selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kemuzuhe
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    int updateByExampleSelective(@Param("record") Kemuzuhe record, @Param("example") KemuzuheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kemuzuhe
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    int updateByExample(@Param("record") Kemuzuhe record, @Param("example") KemuzuheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kemuzuhe
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    int updateByPrimaryKeySelective(Kemuzuhe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kemuzuhe
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    int updateByPrimaryKey(Kemuzuhe record);
}