package cn.xvkang.dao;

import cn.xvkang.entity.Kemu;
import cn.xvkang.entity.KemuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KemuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kemu
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    long countByExample(KemuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kemu
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    int deleteByExample(KemuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kemu
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kemu
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    int insert(Kemu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kemu
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    int insertSelective(Kemu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kemu
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    List<Kemu> selectByExample(KemuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kemu
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    Kemu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kemu
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    int updateByExampleSelective(@Param("record") Kemu record, @Param("example") KemuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kemu
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    int updateByExample(@Param("record") Kemu record, @Param("example") KemuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kemu
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    int updateByPrimaryKeySelective(Kemu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kemu
     *
     * @mbg.generated Wed Apr 24 10:17:12 CST 2019
     */
    int updateByPrimaryKey(Kemu record);
}